# This has to be the absolute path to the RIOT base directory:
RIOTBASE ?= $(CURDIR)/../RIOT

# name of the application
APPLICATION = atecc608a_config_lock
BOARD ?= nrf52840dk

USEPKG += cryptoauthlib

include $(RIOTBASE)/Makefile.include
